name: CI

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
    paths-ignore:
      - 'README.md'

jobs:
  build-windows:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '-SNAPSHOT')"
    steps:
      - uses: actions/checkout@v1
      - run: CALL gradlew.bat --no-daemon jvmTest
        shell: cmd
      - run: CALL gradlew.bat --no-daemon assemble check -x jsBrowserTest -x jsNodeTest
        shell: cmd

  build-mac:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '-SNAPSHOT')"
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew jvmTest
      - run: ./gradlew check -x jsBrowserTest -x jsNodeTest

  build-linux:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '-SNAPSHOT')"
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew jvmTest
      - run: ./gradlew check lint testDebugUnitTest -x jsBrowserTest -x jsNodeTest
